BookStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.DO.Entities;
using BookStore.Models;
using BookStore.DLL.Interface.Abstract;
using System.Net;
using System.IO;
using System.Web.Hosting;
using NLog;

namespace BookStore.Controllers
{

    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly IBookService _bookService;
        private readonly IGenreService _genreService;
        private readonly IAuthorService _authorService;

        public AdminController(IBookService bookService, IGenreService genreService, IAuthorService authorService)
        {
            _bookService = bookService;
            _genreService = genreService;
            _authorService = authorService;
        }

        public ViewResult Edit(int bookId)
        {
            Book book = _bookService.GetById(bookId);
            return View(book);
        }

        public ViewResult EditAuthor(int authorId)
        {
            Author auth = _authorService.GetById(authorId);
            return View(auth);
        }

        public ViewResult Index()
        {
            return View(_bookService.GetAllWithDetails());
        }

        public ViewResult Create()
        {
            return View(new Book { BookAuthors = new List<Author> { new Author() },BookDetail = new BookDetail()});
        }

        [HttpPost]
        public ActionResult FindImage(string title, string lastName, string firstName, int Id)
        {
            string query;
            ViewData["ID"] = Id;
            if (title != null)
            {
                ViewData["Type"] = TypeSearch.BookCover;
                query = string.Format("{0} {1} {2}", title, lastName, firstName);
            }
            else
            {
                ViewData["Type"] = TypeSearch.AuthorPic;
                query = string.Format("author" + " {0} {1}", lastName, firstName);
            }

            logger.Info(query);
            IList<SearchResult> searchResults = SearchResult.GetSearch(query, "&searchType=image");
            
            return PartialView(searchResults.Select(x => x.Link));
        }

        [HttpPost]
        public string CopyImageToHost(string imageUrl, int id, string typesearch)
        {
            var httpWebRequest = (HttpWebRequest)WebRequest.Create(imageUrl);
            httpWebRequest.AllowAutoRedirect = false;
            var ex = imageUrl.Split('.');
            string typePic;
            if (typesearch == TypeSearch.BookCover.ToString())
            {
                typePic = "imgBook";
            }
            else
            {
                typePic = "imgAuthor";
            }
            var imgName = string.Format("{0}{1}{2}{3}", typePic, id, '.', ex.Last());
            var dbUrl = "~/Content/Images/" + imgName;
            var svUrl = Server.MapPath("~/Content/Images/");
            var path = string.Format(svUrl + imgName);

            using (var fileStream = System.IO.File.Create(path))
            {
                using (var httpWebResponse = (HttpWebResponse)httpWebRequest.GetResponse())
                {
                    using (var stream = httpWebResponse.GetResponseStream())
                    {
                        stream.CopyTo(fileStream);
                    }
                }
            }
            return dbUrl;
        }
        [HttpPost]
        public ActionResult FindBookAnnotation(string title, string lastName, string firstName, int bookId)
        {
            string query = string.Format("{0} {1} {2}", title, lastName, firstName);
            logger.Info(query);
            List<string> links = SearchResult.GetSearch(query).Select(x => x.Link).ToList();
            ViewData["BookID"] = bookId;
            return PartialView(SearchResult.GetInnerText(links));
        }

        [HttpPost]
        public ActionResult Create(Book book)
        {
            //if (ModelState.IsValid)
            //{
                _bookService.Create(book);
                logger.Info(book.Title + " created");
                TempData["message"] = string.Format("{0} has been saved", book.Title);
                return RedirectToAction("Edit", new { bookID = book.Book_ID });
            //}
           // return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book)
        {
            //if (ModelState.IsValid)
            //{
                _bookService.Save(book);
                logger.Info(book.Title + " edited");
                TempData["message"] = string.Format("{0} has been saved", book.Title);
                return RedirectToAction("Index");
            //}
            return View(book);
        }

        [HttpPost]
        public ActionResult Delete(int bookId)
        {
            Book deletedBook = _bookService.Delete(bookId);

            if (deletedBook != null)
            {
                logger.Info(deletedBook.Title + " deleted");
                TempData["message"] = string.Format("{0} was deleted", deletedBook.Title);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public string UploadFiles()
        {
            string name=null;
            string author = Request.Params[0];
            string title = Request.Params[1].Replace(" ", "_");
            foreach (string file in Request.Files)
            {
                HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
               // name=Request.Files[file]
                if (hpf.ContentLength == 0)
                    continue;
                name = string.Format("{0}_{1}.{2}", author, title, hpf.FileName.Split('.').Last());
                string savedFileName = Path.Combine(Server.MapPath("~/Content/Books"), name);
                hpf.SaveAs(savedFileName);
            }
            return "~/Content/Books/"+name ;
        }

        [HttpPost]
        public ActionResult EditAuthor(Author auth)
        {
            if (ModelState.IsValid)
            {
                _authorService.Save(auth);
                logger.Info(auth.Last_Name + " " + " edited");
                TempData["message"] = string.Format("{0} has been saved", auth.Last_Name + " ");
                return RedirectToAction("Index");
            }
            return View(auth);
        }
        [HttpGet]
        public ActionResult DeleteAuthor(int authId)
        {
            Author deletedAuth = _authorService.Delete(authId);

            if (deletedAuth != null)
            {
                logger.Info(deletedAuth.Last_Name + " dletedted");
                TempData["message"] = string.Format("{0} was deleted", deletedAuth.Last_Name);
            }
            return RedirectToAction("Index");
        }
    }
}

BookStore/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.DLL.Interface.Abstract;
using BookStore.DO.Entities;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        public ActionResult Index(int authorId)
        {
            Author author=_authorService.GetById(authorId);
            return View(author);
        }
    }
}

BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using BookStore.DO.Entities;
using BookStore.Models;
using BookStore.DLL.Interface.Abstract;

namespace BookStore.Controllers
{
    public class BookController : Controller//TODO: BookDetails
    {
        private readonly IBookService _bookService;

        private readonly IAuthorService _authorService;
        private readonly IUserService _userService;
        // private IGenreService _genreService;
        private const int PageSize = 10;

        private readonly log4net.ILog logger =
            log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public BookController(IBookService bookService, IAuthorService authorService, IUserService userService)
        {
            _bookService = bookService;
            _authorService = authorService;
            _userService = userService;
            //_genreService = genre_service;
        }

        public ViewResult BookDetails(int bookId)//TODO:Different by id
        {
            Book book = _bookService.GetById(bookId);
            int userId = Session["UserId"] == null ? 0 : (int)Session["UserId"];
            var rated = book.BookDetail.RatedUsers.Where(x => x.IsSuggestion == false);
            List<CommentModel> commentModels = new List<CommentModel>();
            bool isRated = false;
            float average = !rated.Any() ? 0 : rated.Select(x => x.RateValue).Average();
            if (rated.Any() && userId != 0)
            {
                isRated = rated.Select(x => x.User.User_ID).Contains(userId) || book.BookDetail.WishedUsers.Select(x => x.User_ID).Contains(userId);
            }
            foreach (Comment com in book.BookDetail.Comments)
            {
                var user = _userService.GetById(com.User.User_ID);
                commentModels.Add(new CommentModel(user.Email, user.Profile.Avatar_Url, com.Context, com.DataCreate));
            }
            int[] ratesCount = new int[10];
            for (int i = 1; i <= 10; i++)
            {
                ratesCount[i - 1] = (rated.Select(x => x.RateValue).Count(x => x == (float)i));
            }
            BookViewModel bookView = new BookViewModel()
            {
                Book = book,
                RatedUsersCount = rated.Count(),
                AverageMark = average,
                WishedUsersCounter = book.BookDetail.WishedUsers.Count,
                IsReadedOrWished = isRated,
                Comments = commentModels
            };
            return View("BookSummary", bookView);
        }
        public JsonResult BarGraph(int bookId)
        {
            List<int> ratesCount = new List<int>();
            for (int i = 1; i <= 10; i++)
            {
                ratesCount.Add(_bookService.GetById(bookId).BookDetail.RatedUsers.Select(x => x.RateValue).Count(x => x == (float)i));
            }
            return Json(ratesCount, JsonRequestBehavior.AllowGet);
        }

        public ICollection<Book> PaginateBooks(IList<Book> books, int page)
        {
            return books.Skip((page - 1) * PageSize).Take(PageSize).ToList();
        }

        public ViewResult ListByTag(int tagId, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByTag(tagId);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentTag = tagId
            };
            ViewBag.Action = "ListByTag";
            return View("List", model);
        }

        public ViewResult ListByLetter(string selectedLetter, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByLetter(selectedLetter);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentLetter = selectedLetter
            };
            ViewBag.Action = "ListByLetter";
            return View("List", model);
        }
        public ViewResult ListByAuthor(string author, int page = 1)
        {
            IList<Book> books = _authorService.GetBooks(author);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentAuthor = author
            };
            ViewBag.Action = "ListByAuthor";
            return View("List", model);
        }

        public ViewResult ListByGenre(string genre, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByGenre(genre);
            logger.Info(books);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentGenre = genre
            };
            ViewBag.Action = "ListByGenre";
            return View("List", model);
        }

        public ViewResult List(int page = 1)
        {
            IList<Book> books = _bookService.GetAllWithDetails();
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
            };
            ViewBag.Action = "List";
            return View("List", model);
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public ActionResult AddComments(Comment comment)
        {
            _bookService.AddComment(comment);
            return RedirectToAction("BookDetails", new { bookId = _bookService.GetById(comment.Book.Book_ID).Book_ID });
        }
        [HttpGet]
        public PartialViewResult AddComment(int bookId)
        {
            return PartialView("Comment", new Comment { Book = _bookService.GetById(bookId).BookDetail, User=_userService.GetById((int)Session["UserId"]).Profile, DataCreate = DateTime.Now });
        }

        public PartialViewResult BookRating(int bookId)
        {
            Rate rate = _bookService.GetRate(bookId, (int)Session["UserId"]);
            rate = rate ?? new Rate { Book = _bookService.GetById(bookId).BookDetail, IsSuggestion = false };
            return PartialView("BookRating", rate);
        }

        [HttpPost]
        public JsonResult GetNames()//TODO: Create class for search in DLL
        {
            var t = _bookService.GetAll().Select(x => new { id = x.Book_ID, name = x.Title, type = 1 }).ToList();
            var a = _authorService.GetAll().Select(x => new { id = x.Author_ID, name = x.Last_Name, type = 2 }).ToList();
            t.AddRange(a);
            var p = Json(t, JsonRequestBehavior.AllowGet);
            return p;
        }

        public ViewResult Fb2Text(string path, int section = 0, int page = 1)
        {
            Fb2Parser fb2 = new Fb2Parser(Server.MapPath(path),section);
            TextViewModel model = new TextViewModel()
            {
                Text = fb2.Text.ToString((page - 1) * fb2.PageCharacters, fb2.PageCharacters)+" - ",
                Chapters = fb2.Chapters,
                CurrentChapter = section,
                PagingInfo = new PagingInfo(page, fb2.PageCharacters, fb2.Text.Length),
                CurrentPath = path
            };
            return View(model);
        }
    }
}

BookStore/Views/Admin/AuthorsView.cshtml
@model BookStore.DO.Entities.Author

@{
    ViewBag.Title = "AuthorsView";
}

<h2>AuthorsView</h2>
@foreach (BookStore.DO.Entities.Book book in @Model.Books)
{
    <p>@book.Title</p>
}

BookStore/Views/Admin/Create.cshtml
@model BookStore.DO.Entities.Book

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { @class = "basic-grey" }))
{
    <h1><span>Создать</span></h1>
    <label>
        <span>@Html.DisplayNameFor(x=>x.Title)</span>
        @Html.EditorFor(b => b.Title, new { @class = "single-line" })
    </label>
    <label>
    </label>
    @Html.EditorFor(b => b.BookAuthors, new { @class = "single-line" })
    <label>
        <span>@Html.ActionLink("Назад", "Index", new {@class = "button"})</span>
        <input type="submit" class="button" value="Сохранить"/>
    </label>
    @Html.HiddenFor(x=>x.Book_ID)
    @Html.HiddenFor(x=>x.BookDetail)
}

BookStore/Views/Admin/Edit.cshtml
@model BookStore.DO.Entities.Book
@using BookStore.HtmlHelpers
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4" id="edit">
            <h2>Edit</h2>
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(b => b.Book_ID)
                <div class="editor-label">@Html.LabelFor(b => b.Title, new {@class = "single-line"})</div>
                <div class="editor-field">@Html.EditorFor(b => b.Title, new {@class = "single-line"})</div>
                <div id="Authors">
                    <a href="#" class="glyphicon glyphicon-plus" aria-hidden="true" onclick=" return addField('Author') "></a>
                    @Html.EditorFor(b => b.BookAuthors, new {@class = "single-line"})
                </div>
                <div class="editor-label">
                    @Html.LabelFor(b => b.BookDetail.Genres, new {@class = "single-line"})
                    <a href="#" class="glyphicon glyphicon-plus" aria-hidden="true" onclick=" return addField('Genre') "></a>
                </div>
                <div id="Genres">
                    @Html.EditorFor(b => b.BookDetail.Genres, new {@class = "single-line"})
                </div>
                <div class="editor-label">
                    @Ajax.ActionLink("Search Annotation", "FindBookAnnotation", "Admin",
                        new {title = @Model.Title, lastName = @Model.BookAuthors.First().Last_Name, firstName = @Model.BookAuthors.First().First_Name, bookId = @Model.Book_ID},
                        new AjaxOptions {UpdateTargetId = "search", InsertionMode = InsertionMode.Replace, HttpMethod = "POST"})
                </div>
                <div class="editor-field">@Html.TextAreaFor(b => b.BookDetail.Annotation, new {@class = "text-box multi-line", id = "AreaText"})</div>
                <div class="editor-label">
                    @Ajax.ActionLink("Search Image", "FindImage", "Admin",
                        new {title = @Model.Title, lastName = @Model.BookAuthors.First().Last_Name, firstName = @Model.BookAuthors.First().First_Name, Id = @Model.Book_ID},
                        new AjaxOptions {UpdateTargetId = "search", InsertionMode = InsertionMode.Replace, HttpMethod = "POST"})
                </div>
                <div class="editor-field">@Html.EditorFor(b => b.Image_url, new {htmlAttributes=new {@class = "single-line", id = "image"}})</div>
                <div class="editor-label">@Html.LabelFor(b => b.BookDetail.Price, new { @class = "single-line" })</div>
                <div class="editor-field">@Html.EditorFor(b => b.BookDetail.Price, new { @class = "single-line", type = "number", step = "any" })</div>
                <div class="editor-label">
                    @Html.LabelFor(b => b.BookDetail.Tages, new { @class = "single-line" })
                    <a href="#" id="addField" class="glyphicon glyphicon-plus" aria-hidden="true" onclick=" return addField('Tag') "></a>
                </div>
                <div class="editor-field" id="Tags">
                    @Html.EditorFor(t => t.BookDetail.Tages, new { @class = "single-line" })
                </div>
                <div class="editor-label">@Html.LabelFor(b => b.BookDetail.ContentUrl, new { @class = "single-line" })</div>
                <div class="editor-field">@Html.EditorFor(b => b.BookDetail.ContentUrl, new { @class = "single-line" })</div>
                <input type="submit" class="btn-default btn" value="Сохранить" />
                <button class="btn-default btn" href="@Url.Action("Index","Admin")">Отменить</button>
            }
        </div>
        <div class="col-md-8">
            <div class="file">
                <input type="file" class="ui-autocomplete-input" name="upload" id="file_upload" />
                <button class="btn btn-primary glyphicon glyphicon-upload g-lg" onclick="uploadFile('@Model.Title', '@Model.BookAuthors.First().Last_Name')"></button>
            </div>
            <div id="search"></div>
        </div>
    </div>
</div>

BookStore/Views/Admin/EditAuthor.cshtml
@model BookStore.DO.Entities.Author

@{
    ViewBag.Title = "EditAuthor";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Edit Author</h2>

<div class="col-md-4" id="edit">
    @using (Html.BeginForm())
    {
        @Html.Hidden("Author_ID", @Model.Author_ID)
        <div class="editor-label">@Html.LabelFor(b => b.Last_Name, new { @class = "single-line" })</div>
        <div class="editor-field">@Html.EditorFor(b => b.Last_Name, new { @class = "single-line" })</div>
        <div class="editor-label">@Html.LabelFor(b => b.First_Name, new { @class = "single-line" })</div>
        <div class="editor-field">@Html.EditorFor(b => b.First_Name, new { @class = "single-line" })</div>
        <div class="editor-label">@Html.LabelFor(b => b.Middle_Name, new { @class = "single-line" })</div>
        <div class="editor-field">@Html.EditorFor(b => b.Middle_Name, new { @class = "single-line" })</div>
        <div class="editor-label">
            @Ajax.ActionLink("Search Biography", "FindBookAnnotation", "Admin",
                  new { title = "", lastName = @Model.Last_Name, firstName = @Model.First_Name, bookId = @Model.Author_ID },
                new AjaxOptions { UpdateTargetId = "search", InsertionMode = InsertionMode.Replace, HttpMethod = "POST" })
        </div>
        <div class="editor-field">@Html.TextAreaFor(b => b.AuthorDetail.Biography, new { @class = "text-box multi-line", id = "AreaText" })</div>
        @*<div class="editor-label">@Html.LabelFor(b => b.Rating, new { @class = "single-line" })</div>
        <div class="editor-field">@Html.EditorFor(b => b.Rating, new { @class = "single-line", type = "number", step = "any" })</div>*@
        <div class="editor-label">
            @Ajax.ActionLink("Load Image", "FindImage", "Admin",
                new { title = "", lastName = @Model.Last_Name, firstName = @Model.First_Name, Id = @Model.Author_ID },
                new AjaxOptions { UpdateTargetId = "search", InsertionMode = InsertionMode.Replace, HttpMethod = "POST" })
        </div>
        <div class="editor-field">@Html.EditorFor(b => b.AuthorDetail.Image_url,new {htmlAttributes= new {@class = "single-line",id="image"}})</div>
    <p>
        <input type="submit" class="btn-default btn" value="Save" />
        @Html.ActionLink("Delete", "DeleteAuthor", new { authId = Model.Author_ID }, new { @class = "btn-default btn" })
        @Html.ActionLink("Back to List", "index", null, new { @class = "btn-default btn" })
    </p>
    }
</div>
<div class="col-md-8">
    <div id="search"></div>
</div>

BookStore/Views/Admin/FindBookAnnotation.cshtml
@model List<string>

@{
    ViewBag.Title = "Find Information";
    Layout = null;
}

<h2>Найденные аннотации</h2>
@foreach (string result in @Model)
{
    <span class="search">
        <p class="description" onclick="return SaveDesc($(this))">@result</p>
    </span>
}

BookStore/Views/Admin/FindImage.cshtml
@using BookStore.HtmlHelpers
@model IEnumerable<string>
@{
    ViewBag.Title = "FindImages";
    Layout = null;

}
@{
    int Id = (int) ViewData["ID"];
    string types = ((BookStore.Models.TypeSearch)ViewData["Type"]).ToString();
}
<h2>Найденные изображения</h2>
@foreach (var result in @Model)
{
    <span class="search">
       <img src="@result" alt="Found book's cover" onclick="return saveImage($(this),@Id,'@types')" class=" bookcover" /> 
    </span>
}

    

BookStore/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.DO.Entities.Book>

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Books</h2>
<div class="links">
    @Html.ActionLink("Create New", "Create", "Admin", null, new { @class = "btn btn-default" })
    @Html.ActionLink("Home", "List", "Book", null, new { @class = "btn btn-default" })
</div>

<table class="Grid table table-condensed table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>

        <th>Авторы</th>
        @*<th class="NumericCol">
            @Html.DisplayNameFor(model => model.BookDetail.Rating)
        </th>*@
        <th class="NumericCol">
            @Html.DisplayNameFor(model => model.BookDetail.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookDetail.Annotation)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.ActionLink(item.Title, "Edit", new { bookID = item.Book_ID })</td>
            <td>
                @foreach (var auth in item.BookAuthors)
                {
                    <p>
                        @Html.ActionLink(string.Concat(Html.DisplayFor(modelItem => auth.First_Name), " ",
                                 Html.DisplayFor(modelItem => auth.Middle_Name), " ",
                                 Html.DisplayFor(modelItem => auth.Last_Name)), "EditAuthor", new { authorId = auth.Author_ID })
                    </p>
                }
            </td>
            @*<td>@Html.DisplayFor(modelItem => item.Rating)</td>*@
            <td>@Html.DisplayFor(modelItem => item.BookDetail.Price)</td>
            <td><p class="annotation">@Html.DisplayFor(modelItem => item.BookDetail.Annotation)</p></td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("BookID", item.Book_ID)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>