BookStore/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.DLL.Interface.Abstract;
using BookStore.DO.Entities;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        public ActionResult Index(int authorId)
        {
            Author author=_authorService.GetById(authorId);
            return View(author);
        }
    }
}

BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using BookStore.DO.Entities;
using BookStore.Models;
using BookStore.DLL.Interface.Abstract;

namespace BookStore.Controllers
{
    public class BookController : Controller//TODO: BookDetails
    {
        private readonly IBookService _bookService;

        private readonly IAuthorService _authorService;
        private readonly IUserService _userService;
        // private IGenreService _genreService;
        private const int PageSize = 10;

        private readonly log4net.ILog logger =
            log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public BookController(IBookService bookService, IAuthorService authorService, IUserService userService)
        {
            _bookService = bookService;
            _authorService = authorService;
            _userService = userService;
            //_genreService = genre_service;
        }

        public ViewResult BookDetails(int bookId)//TODO:Different by id
        {
            Book book = _bookService.GetById(bookId);
            int userId = Session["UserId"] == null ? 0 : (int)Session["UserId"];
            var rated = book.BookDetail.RatedUsers.Where(x => x.IsSuggestion == false);
            List<CommentModel> commentModels = new List<CommentModel>();
            bool isRated = false;
            float average = !rated.Any() ? 0 : rated.Select(x => x.RateValue).Average();
            if (rated.Any() && userId != 0)
            {
                isRated = rated.Select(x => x.User.User_ID).Contains(userId) || book.BookDetail.WishedUsers.Select(x => x.User_ID).Contains(userId);
            }
            foreach (Comment com in book.BookDetail.Comments)
            {
                var user = _userService.GetById(com.User.User_ID);
                commentModels.Add(new CommentModel(user.Email, user.Profile.Avatar_Url, com.Context, com.DataCreate));
            }
            int[] ratesCount = new int[10];
            for (int i = 1; i <= 10; i++)
            {
                ratesCount[i - 1] = (rated.Select(x => x.RateValue).Count(x => x == (float)i));
            }
            BookViewModel bookView = new BookViewModel()
            {
                Book = book,
                RatedUsersCount = rated.Count(),
                AverageMark = average,
                WishedUsersCounter = book.BookDetail.WishedUsers.Count,
                IsReadedOrWished = isRated,
                Comments = commentModels
            };
            return View("BookSummary", bookView);
        }
        public JsonResult BarGraph(int bookId)
        {
            List<int> ratesCount = new List<int>();
            for (int i = 1; i <= 10; i++)
            {
                ratesCount.Add(_bookService.GetById(bookId).BookDetail.RatedUsers.Select(x => x.RateValue).Count(x => x == (float)i));
            }
            return Json(ratesCount, JsonRequestBehavior.AllowGet);
        }

        public ICollection<Book> PaginateBooks(IList<Book> books, int page)
        {
            return books.Skip((page - 1) * PageSize).Take(PageSize).ToList();
        }

        public ViewResult ListByTag(int tagId, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByTag(tagId);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentTag = tagId
            };
            ViewBag.Action = "ListByTag";
            return View("List", model);
        }

        public ViewResult ListByLetter(string selectedLetter, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByLetter(selectedLetter);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentLetter = selectedLetter
            };
            ViewBag.Action = "ListByLetter";
            return View("List", model);
        }
        public ViewResult ListByAuthor(string author, int page = 1)
        {
            IList<Book> books = _authorService.GetBooks(author);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentAuthor = author
            };
            ViewBag.Action = "ListByAuthor";
            return View("List", model);
        }

        public ViewResult ListByGenre(string genre, int page = 1)
        {
            IList<Book> books = _bookService.GetBooksByGenre(genre);
            logger.Info(books);
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
                CurrentGenre = genre
            };
            ViewBag.Action = "ListByGenre";
            return View("List", model);
        }

        public ViewResult List(int page = 1)
        {
            IList<Book> books = _bookService.GetAllWithDetails();
            BookListViewModel model = new BookListViewModel
            {
                Books = PaginateBooks(books, page),
                PagingInfo = new PagingInfo(page, PageSize, books.Count()),
            };
            ViewBag.Action = "List";
            return View("List", model);
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public ActionResult AddComments(Comment comment)
        {
            _bookService.AddComment(comment);
            return RedirectToAction("BookDetails", new { bookId = _bookService.GetById(comment.Book.Book_ID).Book_ID });
        }
        [HttpGet]
        public PartialViewResult AddComment(int bookId)
        {
            return PartialView("Comment", new Comment { Book = _bookService.GetById(bookId).BookDetail, User=_userService.GetById((int)Session["UserId"]).Profile, DataCreate = DateTime.Now });
        }

        public PartialViewResult BookRating(int bookId)
        {
            Rate rate = _bookService.GetRate(bookId, (int)Session["UserId"]);
            rate = rate ?? new Rate { Book = _bookService.GetById(bookId).BookDetail, IsSuggestion = false };
            return PartialView("BookRating", rate);
        }

        [HttpPost]
        public JsonResult GetNames()//TODO: Create class for search in DLL
        {
            var t = _bookService.GetAll().Select(x => new { id = x.Book_ID, name = x.Title, type = 1 }).ToList();
            var a = _authorService.GetAll().Select(x => new { id = x.Author_ID, name = x.Last_Name, type = 2 }).ToList();
            t.AddRange(a);
            var p = Json(t, JsonRequestBehavior.AllowGet);
            return p;
        }

        public ViewResult Fb2Text(string path, int section = 0, int page = 1)
        {
            Fb2Parser fb2 = new Fb2Parser(Server.MapPath(path),section);
            TextViewModel model = new TextViewModel()
            {
                Text = fb2.Text.ToString((page - 1) * fb2.PageCharacters, fb2.PageCharacters)+" - ",
                Chapters = fb2.Chapters,
                CurrentChapter = section,
                PagingInfo = new PagingInfo(page, fb2.PageCharacters, fb2.Text.Length),
                CurrentPath = path
            };
            return View(model);
        }
    }
}

BookStore/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.DLL.Interface.Abstract;
using BookStore.DO.Entities;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class NavController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IGenreService _genreService;
        private readonly IAuthorService _authorService;
        private readonly log4net.ILog logger =
           log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public NavController(IBookService bookService, IGenreService genreService, IAuthorService authorService)
        {
            this._bookService = bookService;
            this._genreService = genreService;
            _authorService = authorService;
        }
        public ActionResult Alphabet(string selectedLetter = null)
        {
            AlphabeticalPagingViewModel model = new AlphabeticalPagingViewModel(selectedLetter, _bookService);
            return PartialView(model);
        }

        public PartialViewResult Menu()
        {
            return PartialView();
        }
        public PartialViewResult Genres(string genre = null)
        {
            IEnumerable<Genre> genres = new List<Genre>();
            if (genre != null)
            {
                Genre currentGenre = _genreService.GetAll().FirstOrDefault(x => x.Genre_Name == genre);
                ViewBag.SelectedGenre = genre;
                genres = _genreService.GetAll().Where(x => x.ParentID == currentGenre.Genre_ID);
                if (genres.Any())
                {
                    ViewBag.ParentName = currentGenre.Genre_Name;
                    return PartialView("NodeGenre",genres);
                }
                else
                {
                    return PartialView("LeafGenre",currentGenre);
                }
            }

            return PartialView(genres);
        }

        public PartialViewResult Authors(string author = null)
        {
            ViewBag.SelectedAuthor = author;
            IEnumerable<string> authors = _authorService
                .GetAll()
                .Select(x => x.Last_Name);
            return PartialView(authors);
        }
    }
}

BookStore/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BookStore.DLL.Interface.Abstract;
using BookStore.DO.Entities;
using NLog;

using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBookService _bookService;
        private readonly IAuthorService _authorService;

        private readonly log4net.ILog logger =
           log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public UserController(IUserService userService, IBookService bookService, IAuthorService authorService)
        {
            _userService = userService;
            _bookService = bookService;
            _authorService = authorService;
        }

        public ActionResult Profile(string user)
        {
            return View(_userService.GetUserByEmail(user));
        }
        [Authorize(Roles = "user")]
        public async Task RateBook(float rate, int bookId, bool isSuggestion)
        {
            int userId = (int)Session["UserId"];
            await _userService.RateBook(rate, userId, bookId, false);
        }

        public int WishBook(int bookId)
        {
            _userService.WishBook(bookId, (int)Session["UserId"]);
            return _bookService.GetById(bookId).BookDetail.WishedUsers.Count;
        }
        [HttpPost]
        public string SaveAvatar()
        {
            string pic = null;
            string user = Request.Params[0].Replace("@", "_").Replace(".", "_");
            HttpPostedFileBase file = Request.Files[0] as HttpPostedFileBase;
            if (file != null)
            {
                pic = "User_" + user + "." + Path.GetFileName(file.FileName).Split('.').Last();
                string path = Path.Combine(Server.MapPath("~/Content/Images/User"), pic);
                // file is uploaded
                file.SaveAs(path);
                // save the image path path to the database or you can send image
                // directly to database
                // in-case if you want to store byte[] ie. for DB
                //using (MemoryStream ms = new MemoryStream())
                //{
                //    file.InputStream.CopyTo(ms);
                //    byte[] array = ms.GetBuffer();
                //}

            }
            // after successfully uploading redirect the user
            return "~/Content/Images/User/" + pic;
        }

        [HttpPost]
        public int FavoriteAuthor(int userId, int authorId)
        {
            _userService.LikeAuthor(authorId, userId);
            return _authorService.GetById(authorId).AuthorDetail.FavoriteUsers.Count;
        }

        public void Suggest()
        {
            _userService.Resuggest1();
        }
    }
}

BookStore/Views/Shared/BookHeader.cshtml
@model BookStore.DO.Entities.Book
<div class="container-fluid ">
    <div class="row bookheader">
        <div class="col-md-1 col-sm-1 smallimage">
            <a href="@Url.Action("BookDetails", "Book", new {bookId = @Model.Book_ID})">
                @if (Model.Image_url != null)
                {
                    <img src="@Url.Content(Model.Image_url)" class="img-thumbnail" alt="images" />
                }
                else
                {
                    <img src="@Url.Content("~/Content/Images/imgBook0.jpg")" class="img-thumbnail" alt="images" />
                }
            </a>
        </div>
        <div class="col-md-11 col-sm-11 ">
            <div class="signature">
                <p class="title">@Model.Title</p>
                @foreach (var author in Model.BookAuthors)
                {
                    <a href="@Url.Action("Index", "Author", new { authorId = author.Author_ID })" class="author">
                        @if (author.First_Name != null)
                        {
                            @author.First_Name.Substring(0, 1);<p>.</p>
                        }
                        @{
                    if (author.Middle_Name != null)
                    {
                        @author.Middle_Name.Substring(0, 1);<p>.</p>
                    }}
                        @author.Last_Name
                    </a>
                }
                @*<p class="glyphicon glyphicon-star rate" aria-hidden="true">@Model.Rating</p>*@

            </div>
            @*<div class="like-rate">
                <p class="price">@Model.BookDetail.Price.ToString("c")</p>
            </div>*@
        </div>

    </div>
</div>

BookStore/Views/Shared/BookSummary.cshtml
@model BookStore.Models.BookViewModel
<script src="~/scripts/chart.min.js"></script>
<div class="container-fluid book ">
    <div class="row itemb">
        <div class="col-md-9 col-lg-9 ">
            <p class="title">@Model.Book.Title</p>
            @Html.HiddenFor(x => x.Book.Book_ID, new { id = "thisBookId" })
            @foreach (var author in Model.Book.BookAuthors)
            {
                <a href="@Url.Action("Index", "Author", new {authorId = author.Author_ID})" class="author">
                    @author.First_Name @author.Middle_Name @author.Last_Name
                </a>
            }
            <br />
            <div class="genre">
                @foreach (var genre in Model.Book.BookDetail.Genres)
                {
                    <a href="@Url.Action("ListByGenre", "Book", new { genre = @genre.Genre_Name })">@genre.Genre_Name</a>
                }
            </div>
            <p class="annotation">@Model.Book.BookDetail.Annotation</p>
            <p class="price">@Model.Book.BookDetail.Price.ToString("c")</p>
            <div class="tags">
                <p>Теги:</p>
                @foreach (var tag in @Model.Book.BookDetail.Tages)
                {
                    @Html.ActionLink(tag.Tag_Name, "ListByTag", "Book", new { tagID = tag.Tag_ID }, null)
                }
            </div>
            <br />
            <div class="myRate">
                @{
                    if (Session["UserId"] != null)
                    {
                        Html.RenderAction("BookRating", "Book", new { bookId = @Model.Book.Book_ID });
                    }
                }
            </div>
            <div class="comments">
                <div class="detailBox">
                    <div class="actionBox">
                        <ul class="commentList">
                            @{Html.RenderPartial("GetComment", @Model.Comments);}
                        </ul>
                        <div class="form-group form-input">
                            @{
                                if (Session["UserId"] != null)
                                {
                                    Html.RenderAction("AddComment", "Book", new { bookId = @Model.Book.Book_ID });
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-lg-3 image">
            @if (Model.Book.Image_url != null)
            {
                <img src="@Url.Content(Model.Book.Image_url)" class="img-thumbnail" alt="images" />
            }
            else
            {
                <img src="@Url.Content("~/Content/Images/imgBook0.jpg")" class="img-thumbnail" alt="images" />
            }
            <div class="rates">
                <a href="#">
                    <span class="glyphicon glyphicon-star rate" aria-hidden="true">@Model.AverageMark.ToString("F")</span>
                    <span class="badge glyphicon glyphicon-user g-lg">@Model.RatedUsersCount.ToString("D")</span>
                    <span class="badge glyphicon glyphicon-user g-lg" id="wishedUsers">@Model.WishedUsersCounter.ToString("D")</span>
                </a>
            </div>
            @if (Session["UserId"] != null && !@Model.IsReadedOrWished)
            {<div class="wish">
                <a class="btn btn-primary glyphicon glyphicon-heart" id="wish"> Хочу почитать</a>
            </div>
            }
            @if (Model.Book.BookDetail.ContentUrl != null)
            {<div class="fb2">
                @Html.ActionLink("Читать", "Fb2Text", "Book", new { path = @Model.Book.BookDetail.ContentUrl }, new { @class = "btn glyphicon glyphicon-book" })
                <a class="btn glyphicon glyphicon-download" href="@Url.Content(@Model.Book.BookDetail.ContentUrl)">Скачать</a>
            </div>}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="statistic">
                <h2>Статистика</h2>
                <canvas id="myChart" width="600" height="400"></canvas>
                <p>Средняя оценка: @Model.AverageMark.ToString("F")</p>
                <p>Всего оценок: @Model.RatedUsersCount.ToString("D")</p>
            </div>
        </div>
    </div>
</div>

BookStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery-2.1.3.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    @*<script src="~/scripts/jquery.fileupload.js"></script>*@
    <script src="~/scripts/addfield.js"></script>
    <script src="~/scripts/save-image.js"></script>
    <title></title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
            <div class="col-md-0 ">

            </div>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="Message">@TempData["message"]</div>
    }
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }
        $.validator.methods.number = function (value, element) {
        return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
    }
</body>
</html>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/scripts/bootstrap.js"></script>
    <script src="~/scripts/bootstrap3-typeahead.js"></script>

    <link href="~/content/star-rating.css" rel="stylesheet" />
    <script src="~/scripts/star-rating.js"></script>
    <script src="~/scripts/rate.js"></script>
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="container-fluid">
        <div class="row header">
            <div class="col-md-3 logo">
                <a href="/"><h1 id="logo">Book Library</h1></a>
            </div>
            <div class="col-md-6">
                <input id="typeahead" class="typeahead input-lg " placeholder="Поиск" type="text" data-provide="typeahead">

            </div>
            <div class="col-md-3 user">
                @{Html.RenderAction("UserLogin", "Account");}
            </div>
        </div>
        <div class="alphabet row">
            <div class="col-md-12">
                @{Html.RenderAction("Alphabet", "Nav");}
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-lg-3  ">
                <div class="collapse-group genre-container">
                    @{
                        Html.RenderAction("Genres", "Nav", new { genre = "Художественная литература" });
                        Html.RenderAction("Genres", "Nav", new { genre = "Нехудожественная литература" });
                        //Html.RenderAction("Genres", "Nav", new { genre = "Комиксы" });
                    }
                </div>
                @*<a href="@Url.Action("Suggest", "User")" class="btn">Suggest</a>*@
            </div>
            <div class="col-md-9 col-lg-9 content">
                @RenderBody()
            </div>
        </div>
    </div>

    <div id="PopupWrapper"></div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/common")
    @RenderSection("scripts", required: false)

</body>
</html>